### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by ghost** [gorankolak/angular-movie-database#1]
It would help if you made a live demo and linked to it from the README.

**Comment by gorankolak** [comment]
Actually, I've made a live demo. You can see link to it in the short description part of the repository (up on top). I'll put a link into the README file, as well - just to be noticed better.

Here is the [link](http://gorankolak.github.io/angular-movie-database/).

**Comment by ghost** [comment]
Ok, thanks! I just ran the app locally though

**Comment by ghost** [comment]
Are there any improvements, bugs, etc that need work?

**Comment by gorankolak** [comment]
No problem, thanks for checking it out!

I've just finished it a day ago and I'll certainly make some improvements (this small app is a part of my learning process of AngularJS, been working on it for some time now).

**Comment by gorankolak** [comment]
If you find some bugs or have some suggestions, feel free to let me know.

**Comment by ghost** [comment]
Ok. Have you ever worked with Firebase? It's an easy way to store data securely in a database. Also, they integrate well with Angular. I would recommend checking out <a href="https://www.firebase.com">firebase.com</a> to learn more. I was thinking we could hook this up to a database, so that the input is saved and people can come back to view it. Thus it will eventually amount to a giant stack of movie data!

**Comment by ghost** [comment]
I have done some work with firebase. For example, check out my basic Angular/Firebase app <a href="https://github.com/colindevs/messageBoard">messageBoard</a>. Read the README to find out more! It uses Firebase to save messages posted to the "board" that will stay there.

**Comment by ghost** [comment]
A live demo of messageBoard is available <a href="https://test-google-auth.firebaseapp.com">here</a> or from the README!

**Comment by gorankolak** [comment]
I know that saving a large data to the local storage is not a proper way for some real/bigger app. I've made it like this just for starting out.

 I haven't used Firebase yet, but I was going to, planned this to be my next step.
(I took a quick look to your app - I'll check it out in detail later and in the next couple of days, also.)

**Comment by ghost** [comment]
Thanks, and yeah, firebase is a good next step from Angular. Or as least it was for me. I will look into adding a database to the movie app, too.

**Comment by ghost** [comment]
By the way you can close this issue now.
